apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: cache-server
      labels:
        app: cache-server
    spec:
      replicas: 1
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            deploymentConfig: cache-server
            app: cache-server
        spec:
          containers:
            - env:
              - name: DEFAULT_CACHE_EXPIRATION_LIFESPAN
                value: "10000"
              - name: INFINISPAN_CONNECTORS
                value: hotrod
              image: registry.access.redhat.com/jboss-datagrid-7/datagrid72-openshift:1.0
              name: cache-server
              ports:
              - containerPort: 8778
                protocol: TCP
              - containerPort: 11211
                protocol: TCP
              - containerPort: 11222
                protocol: TCP
              - containerPort: 11333
                protocol: TCP
              - containerPort: 8080
                protocol: TCP
              - containerPort: 8443
                protocol: TCP
      triggers:
        - type: ConfigChange
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: cache-server
      name: cache-server
    spec:
      selector:
        app: cache-server
      ports:
      - name: 8080-tcp
        port: 8080
        protocol: TCP
        targetPort: 8080
      - name: 8443-tcp
        port: 8443
        protocol: TCP
        targetPort: 8443
      - name: 8778-tcp
        port: 8778
        protocol: TCP
        targetPort: 8778
      - name: 11211-tcp
        port: 11211
        protocol: TCP
        targetPort: 11211
      - name: 11222-tcp
        port: 11222
        protocol: TCP
        targetPort: 11222
      - name: 11333-tcp
        port: 11333
        protocol: TCP
        targetPort: 11333
      type: ClusterIP
