apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ .Values.datagrid.name }}
  labels:
    app: {{ .Values.datagrid.name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        deploymentConfig: {{ .Values.datagrid.name }}
        app: {{ .Values.datagrid.name }}
    spec:
      containers:
        - env:
            - name: DEFAULT_CACHE_EXPIRATION_LIFESPAN
              value: "10000"
            - name: INFINISPAN_CONNECTORS
              value: hotrod
          image: {{ .Values.datagrid.image }}
          name: cache-server
          ports:
            - containerPort: 8778
              protocol: TCP
            - containerPort: 11211
              protocol: TCP
            - containerPort: 11222
              protocol: TCP
            - containerPort: 11333
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
  triggers:
    - type: ConfigChange
