apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.datagrid.name }}
  name: {{ .Values.datagrid.name }}
spec:
  selector:
    app: {{ .Values.datagrid.name }}
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    - name: 11211-tcp
      port: 11211
      protocol: TCP
      targetPort: 11211
    - name: 11222-tcp
      port: 11222
      protocol: TCP
      targetPort: 11222
    - name: 11333-tcp
      port: 11333
      protocol: TCP
      targetPort: 11333
  type: ClusterIP
